# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'xSchedule-ios' do

end

target 'xSchedule-iosTests' do

end

target 'xSchedule-iosUITests' do

end

